### ISSUE TITLE
not compile -  xcode (Version 8.2.1 (8C1002))

### ISSUE THREAD

**Issue by michelmelo** [elpassion/DropColour-iOS#26]
hi, 
Hello i am trying to compile more of the error in swift 2.2

**Comment by michelmelo** [comment]
`“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

**Comment by mateuszszklarek** [comment]
@michelmelo Thanks for your reported issue! Like you notice it's already solved.
