### ISSUE TITLE
translation 

### ISSUE THREAD

**Issue by michelmelo** [elpassion/DropColour-iOS#29]
Can I do the translation into Portuguese?

**Comment by mateuszszklarek** [comment]
@michelmelo Yes, it would be great! Please write your e-mail, I will send you invitation to Google Docs with translations.

**Comment by michelmelo** [comment]
michellander[a]gmail.com

**Comment by michelmelo** [comment]
@mateuszszklarek  I do not know if you've already sent the invitation. If I can send it, I'll do the translation on the weekend.

**Comment by mateuszszklarek** [comment]
@michelmelo I sent you invitation to google docs file, please let me know if everything is ok and you have proper access to edit file.

**Comment by michelmelo** [comment]
@mateuszszklarek  yes.

**Comment by michelmelo** [comment]
@mateuszszklarek Hi, it's already done, thank you.

**Comment by mateuszszklarek** [comment]
@michelmelo Thank you, I'm going to release portugese language in the nearest version.

**Comment by dmitry-moskalets** [comment]
I can help you with Ukrainian & Russian translations: moskalets.dmitry[a]gmail.com
